#!/bin/bash
cd /tmp/rom
rm -rf .repo
cd external/selinux 
curl -L http://ix.io/2FhM > sasta.patch 
git am sasta.patch 
cd /tmp/rom
source build/envsetup.sh
lunch lineage_CPH1859-eng
export SKIP_API_CHECKS=true
export SKIP_ABI_CHECKS=true
cd /tmp/rom
export CCACHE_DIR=/tmp/ccache  ##use additional flags if you need(optional)
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1

ccache -M 30G
ccache -o compression=true
ccache -z
ccache -c

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_rom(){
	mka recoveryimage
	zip=$(up out/target/product/CPH1859/recovery.img)
	echo " "
	echo "$zip"
	curl -sL https://git.io/file-transfer | sh
	./transfer wet out/target/product/CPH1859/recovery.img
}

make_rom
